#!/usr/bin/env bash
set -eufo pipefail
source "${BASH_SOURCE%/*}/../node_modules/sanctuary-scripts/functions"

branches="$(get min-branch-coverage)"

c8 node --experimental-modules --no-warnings ./node_modules/.bin/oletus
c8 report -r lcov
c8 check-coverage --branches "$branches"
